// src/components/laws/PrincipleCard.tsx
import Link from 'next/link'
import type { PrincipleWithSlug, PrincipleType } from '@/lib/principles-types'
import { TYPE_LABELS } from '@/lib/principles-types'
import { PrincipleArt } from './PrincipleArt'

function typeBadge(type: PrincipleType) {
  switch (type) {
    case 'ux_law':
      return 'bg-sky-950/60 text-sky-400 border-sky-800/40'
    case 'cognitive_bias':
      return 'bg-purple-950/60 text-purple-400 border-purple-800/40'
    case 'heuristic':
      return 'bg-emerald-950/60 text-emerald-400 border-emerald-800/40'
  }
}

export function PrincipleCard({ principle }: { principle: PrincipleWithSlug }) {
  return (
    <Link
      href={`/laws-and-patterns/${principle.slug}`}
      className="group flex flex-col rounded-xl border border-white/8 bg-white/[0.025] hover:bg-white/[0.05] hover:border-white/15 transition-all duration-200 overflow-hidden"
    >
      {/* Generative art thumbnail */}
      <div className="relative w-full aspect-[8/5] overflow-hidden">
        <PrincipleArt
          slug={principle.slug}
          category={principle.category}
          className="w-full h-full"
        />
      </div>

      <div className="flex flex-col gap-4 p-6">
        <div className="flex items-center gap-2 flex-wrap">
          <span
            className={`inline-block px-2.5 py-1 text-[14px] font-semibold uppercase tracking-[0.12em] rounded-full border ${typeBadge(principle.type)}`}
          >
            {TYPE_LABELS[principle.type]}
          </span>
        </div>

        <div>
          <h3 className="font-extrabold text-[18px] text-white leading-snug mb-2 group-hover:text-steel-mist transition-colors">
            {principle.title}
          </h3>
          <p className="text-white/50 leading-[1.55] text-[18px]">
            {principle.oneLiner}
          </p>
        </div>
      </div>
    </Link>
  )
}

// components/PrincipleCard.vue
<template>
  <NuxtLink
    :to="`/laws-and-patterns/${principle.slug}`"
    class="block bg-white border border-gray-200 rounded-xl p-6 hover:shadow-lg transition-shadow"
  >
    <!-- Emoji -->
    <div class="text-3xl mb-3">
      {{ emoji }}
    </div>

    <!-- Title -->
    <h3 class="text-xl font-semibold text-black leading-tight mb-3">
      {{ principle.title }}
    </h3>

    <!-- Description -->
    <p class="text-gray-600 leading-relaxed mb-4">
      {{ principle.oneLiner }}
    </p>

    <!-- Type and Category badges -->
    <div class="flex items-center gap-2 flex-wrap">
      <span :class="typeBadgeClass">
        {{ typeLabel }}
      </span>
      <span :class="categoryBadgeClass">
        {{ categoryLabel }}
      </span>
    </div>
  </NuxtLink>
</template>

<script setup lang="ts">
import type { PrincipleWithSlug } from '~/types/principles';
import { TYPE_COLORS, TYPE_LABELS, getPrincipleEmoji, CATEGORIES } from '~/types/principles';

const props = defineProps<{
  principle: PrincipleWithSlug;
}>();

const typeLabel = computed(() => TYPE_LABELS[props.principle.type]);
const emoji = computed(() => getPrincipleEmoji(props.principle.title));
const categoryLabel = computed(() => CATEGORIES[props.principle.category as keyof typeof CATEGORIES]?.label || props.principle.category);

// Type badge class with static Tailwind classes
const typeBadgeClass = computed(() => {
  const baseClass = 'inline-block px-3 py-1 text-xs font-medium rounded-full';
  switch (props.principle.type) {
    case 'ux_law':
      return `${baseClass} bg-sky-50 text-sky-500`;
    case 'cognitive_bias':
      return `${baseClass} bg-purple-50 text-purple-500`;
    case 'heuristic':
      return `${baseClass} bg-emerald-50 text-emerald-500`;
    default:
      return `${baseClass} bg-gray-100 text-gray-700`;
  }
});

// Category badge class with static Tailwind classes
const categoryBadgeClass = computed(() => {
  const baseClass = 'inline-block px-3 py-1 text-xs font-medium rounded-full';
  switch (props.principle.category) {
    case 'attention':
      return `${baseClass} bg-red-100 text-red-800`;
    case 'memory':
      return `${baseClass} bg-purple-100 text-purple-800`;
    case 'decisions':
      return `${baseClass} bg-green-100 text-green-800`;
    case 'usability':
      return `${baseClass} bg-orange-100 text-orange-800`;
    case 'persuasion':
      return `${baseClass} bg-pink-100 text-pink-800`;
    case 'visual':
      return `${baseClass} bg-indigo-100 text-indigo-800`;
    default:
      return `${baseClass} bg-gray-100 text-gray-800`;
  }
});
</script>
